from common import sources_block

def _page(eyebrow, title, intro, content, updated="2026-09-08"):
    return f"""
<div class="page-title"><div class="wrap"><span class="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p><div class="meta-line">Last updated {updated}</div></div></div>
<section><div class="wrap prose">{content}</div></section>
"""

def privacy(ctx):
    e = ctx["CONTACT_EMAIL"]
    return _page("Legal", "Privacy policy", "How Wallet Partners LLC handles personal data collected through this website and in the course of its business.", f"""
<h2>1. Who we are</h2>
<p>Wallet Partners LLC ("Wallet Partners", "we") operates this website. For questions about this policy or to exercise your rights, write to <a href="mailto:{e}">{e}</a>.</p>
<h2>2. Data we collect on this website</h2>
<ul>
<li><strong>Contact form.</strong> Name, organisation, email address, the role you select and the content of your message. We use it to reply to you and to keep a record of the enquiry.</li>
<li><strong>Server logs.</strong> Our hosting provider, Cloudflare, processes IP addresses, user-agent strings and request metadata to deliver the site, protect it from abuse and produce aggregate traffic statistics. Cloudflare's processing is governed by its own privacy policy.</li>
<li><strong>Local storage.</strong> One key in your browser records that you dismissed the cookie notice. It contains no identifier. See the <a href="/legal/cookies/">cookie notice</a>.</li>
</ul>
<p>We do not use advertising trackers, analytics scripts or social-media pixels. Map tiles are loaded from CARTO and OpenStreetMap servers; those providers receive your IP address when the tiles and scripts are requested.</p>
<h2>3. Data we collect in our business</h2>
<p>When a gasoline station applies to join our program we collect the information a sponsoring bank and the card networks require to underwrite a merchant: legal-entity details and RNC, operating licences, identity documents and contact details of owners, directors and beneficial owners, bank account details for settlement, and transaction data generated by card acceptance. This data is processed to perform the merchant agreement, to comply with legal obligations (including anti-money-laundering rules under Dominican Law 155-17 and applicable U.S. law) and to protect against fraud.</p>
<h2>4. Legal bases and applicable law</h2>
<p>We process personal data of Dominican residents in accordance with Law No. 172-13 on the Protection of Personal Data and, where applicable, Law No. 183-02 and the regulations of the Monetary Board and the Superintendency of Banks. Data relating to U.S. persons is processed under applicable U.S. federal and state law. Where consent is the basis, you may withdraw it at any time without affecting prior processing.</p>
<h2>5. Sharing</h2>
<p>We share personal data only with: the sponsoring bank and card networks, as required to provide acquiring services; service providers acting on our instructions (hosting, email delivery, terminal management, KYC screening); professional advisers; and public authorities where the law requires it. We do not sell personal data.</p>
<h2>6. International transfers</h2>
<p>Because Wallet Partners is organised in the United States and uses cloud providers, data may be processed outside the Dominican Republic. We use contractual safeguards with providers and apply the security measures described below.</p>
<h2>7. Retention</h2>
<p>Website enquiries are kept for up to 24 months. Merchant and transaction records are kept for the periods required by card-network rules and by Dominican and U.S. law, generally at least five years after the relationship ends, or ten years where Law 155-17 requires it.</p>
<h2>8. Security</h2>
<p>We apply encryption in transit (TLS) and at rest, role-based access, logging and vendor due diligence. Cardholder data is never stored on this website; payment terminals in our program use point-to-point encryption and we operate under PCI DSS.</p>
<h2>9. Your rights</h2>
<p>Subject to applicable law you may request access to, correction, deletion or portability of your data, object to or restrict processing, and complain to a supervisory authority. In the Dominican Republic, Law 172-13 rights may be exercised with us directly and, for credit-information matters, before the Superintendency of Banks. Requests go to <a href="mailto:{e}">{e}</a>; we respond within the statutory period.</p>
<h2>10. Children</h2>
<p>This website is intended for businesses and is not directed at children under 18. We do not knowingly collect their data.</p>
<h2>11. Changes</h2>
<p>We may update this policy. The date at the top shows the latest revision; material changes will be highlighted on this page.</p>
""")

def terms(ctx):
    e = ctx["CONTACT_EMAIL"]
    return _page("Legal", "Terms of use", "The conditions under which you may use this website.", f"""
<h2>1. Acceptance</h2><p>By using this website you agree to these terms. If you do not agree, please do not use the site.</p>
<h2>2. Purpose of the site</h2><p>This site presents Wallet Partners LLC's proposed card-acceptance program for fuel retailers in the Dominican Republic to prospective sponsoring banks, partners and merchants. It is informational. Nothing on it constitutes an offer of banking, payment or financial services, a solicitation to invest, or financial, legal or tax advice.</p>
<h2>3. Market information</h2><p>Market figures are quoted from public sources identified on the relevant pages, as published, and may be revised by their authors. The scenario calculator produces illustrative arithmetic from the assumptions you enter and is not a forecast, projection or offer. Station information was compiled from public listings and may change; verify before relying on it.</p>
<h2>4. No banking relationship</h2><p>Wallet Partners LLC is not a bank, not a licensed financial intermediary in the Dominican Republic and not a member of any card network in its own right. Card-acceptance services described here will be provided only once a sponsorship agreement with a licensed member financial institution is in force, under that institution's rules and applicable law.</p>
<h2>5. Intellectual property</h2><p>Text, graphics, code and the compiled station dataset are © Wallet Partners LLC unless otherwise stated. You may download the station data files for evaluation of our proposal. Map data is © OpenStreetMap contributors (ODbL) and basemap styling © CARTO. Fuel brand names belong to their respective owners and appear only to identify locations; no affiliation or endorsement is implied.</p>
<h2>6. Acceptable use</h2><p>You may not attempt to gain unauthorised access to the site or its hosting, scrape it in a way that burdens the service, or use it for unlawful purposes. Security researchers should follow the process in our <a href="/.well-known/security.txt">security.txt</a>.</p>
<h2>7. Third-party links</h2><p>Links to news sources, regulators and map services are provided for convenience. We do not control and are not responsible for their content.</p>
<h2>8. Disclaimer and limitation of liability</h2><p>The site is provided "as is". To the fullest extent permitted by law we exclude all warranties and will not be liable for any loss arising from use of the site or reliance on its content.</p>
<h2>9. Governing law</h2><p>These terms are governed by the laws of the State in which Wallet Partners LLC is organised and, for users in the Dominican Republic, without prejudice to mandatory consumer-protection rules under Law No. 358-05.</p>
<h2>10. Contact</h2><p><a href="mailto:{e}">{e}</a></p>
""")

def cookies(ctx):
    return _page("Legal", "Cookie notice", "This site is deliberately light on cookies. Here is exactly what it stores.", """
<h2>What we store</h2>
<div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Purpose</th><th>Duration</th></tr></thead><tbody>
<tr><td><span class="kbd">wp_cookie_notice</span></td><td>localStorage (not a cookie)</td><td>Remembers that you dismissed the cookie notice</td><td>Until you clear site data</td></tr>
<tr><td><span class="kbd">__cf_bm</span>, <span class="kbd">cf_clearance</span> (only if triggered)</td><td>Cookie set by Cloudflare</td><td>Bot protection and security challenges for the hosting platform</td><td>Up to 30 minutes / as set by Cloudflare</td></tr>
</tbody></table></div>
<h2>What we do not use</h2>
<p>No analytics cookies, no advertising cookies, no social-media plug-ins, no cross-site tracking. Cloudflare Web Analytics, if enabled later, is cookieless and does not fingerprint visitors.</p>
<h2>Third-party content</h2>
<p>The interactive map loads map tiles from CARTO / OpenStreetMap. Those requests reveal your IP address to the provider but set no cookies on this site.</p>
<h2>Your choices</h2>
<p>You can clear or block local storage and cookies in your browser settings. Blocking them does not affect the site's content; the notice will simply reappear.</p>
""")

def compliance(ctx):
    return _page("Compliance", "Compliance & regulatory framework", "How Wallet Partners LLC intends to operate within card-network rules, Dominican financial regulation and the oversight of a sponsoring bank. This page summarises the programme; full policies are available to prospective sponsors under NDA.", f"""
<div class="callout info"><p><strong>Status.</strong> Wallet Partners is pre-launch. The controls below describe the programme we are building to the standard a sponsoring bank will require. Items marked as "at launch" will be validated before the first live transaction.</p></div>

<h2>1. Regulatory map</h2>
<h3>Dominican Republic</h3>
<ul>
<li><strong>Law No. 183-02, Monetary and Financial Law</strong>, and the Monetary Board's <strong>Payment Systems Regulation (SIPARD)</strong>, most recently amended in August 2025. The Banco Central de la República Dominicana oversees the payment system; card acquiring is performed by or under licensed financial intermediaries supervised by the <strong>Superintendencia de Bancos</strong>. Wallet Partners will operate as a program manager / payment facilitator under a licensed member bank and will register or license any locally required entity.</li>
<li><strong>Law No. 155-17 against money laundering and terrorist financing</strong>, its regulations and the guidance of the Unidad de Análisis Financiero (UAF): merchant due diligence, beneficial-ownership identification, transaction monitoring, record-keeping and suspicious-transaction reporting through the sponsoring bank.</li>
<li><strong>Law No. 172-13 on protection of personal data</strong>: lawful processing, security measures and data-subject rights for merchants, their owners and cardholders.</li>
<li><strong>Law No. 358-05 on consumer protection</strong> (Pro Consumidor): transparent pricing, receipts and complaint handling at the point of sale.</li>
<li><strong>Tax.</strong> Dirección General de Impuestos Internos (DGII) rules on card-transaction withholding (Norma General 08-04 and successors) and the fuel-specific tax regime (Laws 112-00 and 557-05, under which retail fuel is subject to selective and ad-valorem taxes rather than ITBIS). Withholding parameters for fuel merchants will be confirmed with the sponsoring bank and tax counsel before launch.</li>
<li><strong>Fuel sector.</strong> Only stations holding a valid operating resolution from the Ministry of Industry, Commerce and MSMEs (MICM) are eligible; the resolution and the station's DGII registration form part of every merchant file.</li>
</ul>
<h3>United States and international</h3>
<ul>
<li><strong>Bank Secrecy Act / AML programme</strong> aligned with the sponsoring bank's requirements and, where applicable, FinCEN registration; <strong>OFAC</strong> and other sanctions screening of all merchants and beneficial owners.</li>
<li><strong>Card-network rules</strong> (Visa Core Rules and Mastercard Rules) for payment facilitators and sponsored merchants, including merchant category codes 5541 (service stations) and 5542 (automated fuel dispensers), automated-fuel-dispenser authorisation and completion rules, and the MATCH / terminated-merchant checks.</li>
<li><strong>PCI DSS v4.0</strong> as a Level 1 service provider at launch, using point-to-point-encrypted (P2PE) terminals so that no cardholder data touches Wallet Partners' systems in clear text.</li>
</ul>

<h2>2. Merchant onboarding (KYB / KYC)</h2>
<ul>
<li>Legal-entity verification: constitutive documents, RNC, commercial registry, MICM operating resolution, proof of address and site photographs.</li>
<li>Identification of directors and every beneficial owner at 10% or more; identity documents; PEP and sanctions screening; adverse-media review.</li>
<li>Financial profile: expected monthly volume, average ticket, card-present share; bank account ownership verification for settlement.</li>
<li>Risk rating and approval workflow: Wallet Partners prepares and recommends; the sponsoring bank approves, conditions or declines. Periodic refresh at least every two years, or on trigger events.</li>
</ul>

<h2>3. Transaction monitoring and fraud</h2>
<ul>
<li>Rules for fuel: per-card and per-pump velocity limits, ticket-size caps consistent with tank capacity, duplicate-transaction detection, unusual night-time patterns, and card-testing detection.</li>
<li>Portfolio monitoring against network chargeback and fraud thresholds; early-warning reporting to the bank.</li>
<li>Escalation of unusual activity to the bank's compliance function; suspicious-transaction reporting through the bank to the UAF and, where applicable, FinCEN.</li>
</ul>

<h2>4. Funds, settlement and reserves</h2>
<ul>
<li>Network settlement is received by the sponsoring bank into a program account it controls. Wallet Partners does not hold merchant funds outside that structure.</li>
<li>Next-business-day settlement to merchants in Dominican pesos, with reserves and delayed-release rules set with the bank per merchant risk tier.</li>
<li>Daily reconciliation of network settlement, merchant payouts, fees and reserves; monthly reporting to the bank.</li>
</ul>

<h2>5. Information security</h2>
<ul>
<li>P2PE-validated terminals; tokenisation for any stored references; no storage of PAN, track or CVV data.</li>
<li>Segmented cloud environment, encryption at rest, key management with dual control, MFA for all administrative access, centralised logging and alerting.</li>
<li>Annual penetration testing, vulnerability management, vendor risk assessments and an incident-response plan with notification timelines agreed with the bank and, where required, under Law 172-13.</li>
<li>Coordinated vulnerability disclosure via <a href="/.well-known/security.txt">security.txt</a>.</li>
</ul>

<h2>6. Governance</h2>
<ul>
<li>Designated compliance officer; board-approved AML, sanctions, privacy and information-security policies; annual independent review.</li>
<li>Training for all staff and field technicians on AML red flags, data protection and card-network rules.</li>
<li>Complete records retained for at least five years (ten where Law 155-17 requires), available to the sponsoring bank and regulators on request; contractual right-to-audit for the bank.</li>
<li>Merchant complaints handled within the terms agreed with the bank and Pro Consumidor rules; escalation path documented on every receipt and statement.</li>
</ul>

<h2>7. Document list available to sponsors</h2>
<ul>
<li>AML/CFT programme and risk assessment</li><li>Sanctions screening procedure</li><li>Merchant underwriting policy and file template</li><li>Transaction-monitoring rule set (fuel)</li><li>Information-security policy set and PCI DSS plan</li><li>Privacy programme (Law 172-13)</li><li>Business-continuity and incident-response plans</li><li>Draft sponsorship term sheet and reserve model</li>
</ul>
{sources_block(["ley_183", "jm_sipard", "sb_normativas"], "Regulatory references")}
""")

def notice(ctx):
    e = ctx["CONTACT_EMAIL"]
    return _page("Legal", "Legal notice", "Identification of the website operator and related disclosures.", f"""
<h2>Website operator</h2>
<p><strong>Wallet Partners LLC</strong><br />A limited liability company organised under the laws of the United States.<br />Email: <a href="mailto:{e}">{e}</a></p>
<p>Registered agent, state of formation and registration number are provided on request and in the sponsor-bank pack; they will be published here on launch together with the details of the Dominican operating affiliate.</p>
<h2>Regulatory status</h2>
<p>Wallet Partners LLC is not a bank, savings institution, money transmitter or licensed financial intermediary in the Dominican Republic and is not currently a registered payment facilitator with any card network. Card-acceptance services will be provided only under a sponsorship agreement with a licensed member financial institution, and the sponsor's identity will be disclosed to merchants in the merchant agreement.</p>
<h2>Trademarks</h2>
<p>"Wallet Partners" and the Wallet Partners logo are trademarks of Wallet Partners LLC. TotalEnergies, Shell, Texaco, Next, Axxon, Tropigás, Sigma, VP Racing, Óptimo Gas, Trovasa, Visa, Mastercard, CardNET, AZUL, Visanet and other names are the property of their respective owners and are used solely to identify locations and market participants. No sponsorship, affiliation or endorsement is implied.</p>
<h2>Content and images</h2>
<p>Station data was compiled from public map listings on {ctx['DATA_DATE']}. Photographic images on this site are AI-generated illustrations and do not depict specific stations, people or brands. Map data © OpenStreetMap contributors, available under the Open Database Licence; basemap © CARTO.</p>
<h2>Hosting</h2>
<p>This site is served by Cloudflare, Inc. Its security headers, transport encryption and DNS configuration are described in the repository documentation.</p>
""")

def accessibility(ctx):
    e = ctx["CONTACT_EMAIL"]
    return _page("Legal", "Accessibility statement", "We want every prospective partner to be able to use this site.", f"""
<p>Wallet Partners LLC aims to conform to the Web Content Accessibility Guidelines (WCAG) 2.2 at level AA. Measures taken on this site include:</p>
<ul><li>Semantic HTML with a skip link, landmarks and a logical heading order.</li><li>Keyboard-operable navigation, filters and forms; visible focus states.</li><li>Colour contrast at or above 4.5:1 for text; information never conveyed by colour alone (map markers carry numbers; charts include table views).</li><li>Text alternatives for images; decorative images marked as such.</li><li>Charts and the station map have accessible names and an equivalent table.</li><li>No motion that cannot be paused; no auto-playing media.</li></ul>
<h2>Known limitations</h2>
<p>The interactive map relies on a third-party library (Leaflet); while markers are keyboard-focusable, panning by keyboard may be limited in some browsers. The station directory table below the map provides the same information.</p>
<h2>Feedback</h2>
<p>If you encounter a barrier, email <a href="mailto:{e}">{e}</a> and we will respond within five business days.</p>
""")

def notfound(ctx):
    return """
<section><div class="wrap center" style="padding:60px 20px">
  <span class="eyebrow">404</span>
  <h1>Page not found</h1>
  <p class="muted">The page you requested does not exist or has moved.</p>
  <div class="hero-actions" style="justify-content:center"><a class="btn btn-navy" href="/">Go to the home page</a><a class="btn btn-outline" href="/stations/">Station map</a></div>
</div></section>
"""
