"""Page registry. Each entry: path, title, description, body(ctx) -> HTML fragment. Site language is Spanish; /en/ is English."""
import home, como, precios, zona, preguntas, afiliese, bancos, en, nosotros, contacto, legal

PAGES = [
    dict(path="/", title="Wallet Partners | Aceptación de tarjetas para estaciones de combustible en República Dominicana",
         description="Acepte tarjetas en su estación de gasolina y pague por galón, no por porcentaje. Liquidación al día siguiente en pesos, terminales para el patio y soporte en Santo Domingo. Wallet Partners LLC.",
         body=home.body, map=True, priority="1.0"),
    dict(path="/como-funciona/", title="Cómo funciona | Wallet Partners",
         description="Cómo funciona la aceptación de tarjetas de Wallet Partners en estaciones de combustible: autorización, liquidación al día siguiente, conciliación por turno, documentos para afiliarse y terminales para el patio.",
         body=como.body, priority="0.8"),
    dict(path="/precios/", title="Precios por galón | Wallet Partners",
         description="Tarifa fija por galón con tope en lugar de una comisión porcentual. Calcule cuánto paga hoy en comisiones por galón con los datos de su estación.",
         body=precios.body, priority="0.9"),
    dict(path="/zona/", title="Zona de lanzamiento: Polígono Central | Wallet Partners",
         description="Mapa de las 20 estaciones de combustible dentro y alrededor del Polígono Central de Santo Domingo donde Wallet Partners inicia sus instalaciones. Registre su estación para la primera ola.",
         body=zona.body, map=True, priority="0.8"),
    dict(path="/preguntas/", title="Preguntas frecuentes | Wallet Partners",
         description="Respuestas para dueños de estaciones: bancos, plazos de liquidación, tarjetas aceptadas, costo de terminales, contracargos, documentos y aprobación.",
         body=preguntas.body, priority="0.7"),
    dict(path="/afiliese/", title="Afilie su estación | Wallet Partners",
         description="Registre su estación de combustible en cinco minutos y reciba una propuesta con la tarifa por galón para su volumen.",
         body=afiliese.body, priority="0.9"),
    dict(path="/bancos/", title="Bancos y aliados | Wallet Partners",
         description="Resumen para bancos patrocinadores y aliados: programa vertical de adquirencia para estaciones de combustible en la República Dominicana, división de responsabilidades, marco de cumplimiento y lo que pedimos.",
         body=bancos.body, priority="0.7"),
    dict(path="/en/", title="For banks & partners | Wallet Partners LLC",
         description="Summary for sponsoring banks and partners: a vertical fuel-retail acquiring program for the Dominican Republic, responsibilities, compliance framework and the ask.",
         body=en.body, lang="en", priority="0.7"),
    dict(path="/nosotros/", title="Nosotros | Wallet Partners LLC",
         description="Wallet Partners LLC es una empresa de pagos dedicada a las estaciones de combustible de la República Dominicana.",
         body=nosotros.body, priority="0.5"),
    dict(path="/contacto/", title="Contacto | Wallet Partners",
         description="Contacte a Wallet Partners LLC: estaciones, bancos, aliados y prensa.", body=contacto.body, priority="0.6"),
    dict(path="/legal/privacidad/", title="Política de privacidad | Wallet Partners", description="Cómo Wallet Partners LLC trata los datos personales, incluida la Ley 172-13.", body=legal.privacy, priority="0.3"),
    dict(path="/legal/terminos/", title="Términos de uso | Wallet Partners", description="Condiciones de uso del sitio web de Wallet Partners LLC.", body=legal.terms, priority="0.3"),
    dict(path="/legal/cookies/", title="Aviso de cookies | Wallet Partners", description="Cookies y almacenamiento local usados por este sitio.", body=legal.cookies, priority="0.3"),
    dict(path="/legal/cumplimiento/", title="Marco de cumplimiento | Wallet Partners", description="Programa de cumplimiento de Wallet Partners LLC: PCI DSS, Ley 155-17, Ley 172-13, reglas de las redes y supervisión del banco patrocinador.", body=legal.compliance, priority="0.5"),
    dict(path="/legal/aviso-legal/", title="Aviso legal | Wallet Partners", description="Identificación de la empresa, marcas y declaraciones del sitio de Wallet Partners LLC.", body=legal.notice, priority="0.3"),
    dict(path="/legal/accesibilidad/", title="Accesibilidad | Wallet Partners", description="Compromisos de accesibilidad del sitio de Wallet Partners LLC.", body=legal.accessibility, priority="0.3"),
    dict(path="/404.html", title="Página no encontrada | Wallet Partners", description="La página solicitada no existe.", body=legal.notfound, robots="noindex, nofollow"),
]
