"""Page registry. Each entry: path, title, description, body(ctx) -> HTML fragment. Site language is Spanish; /en/ is English."""
import home, como, precios, zona, preguntas, afiliese, bancos, nosotros, contacto, legal
import en_pages as E

PAGES = [
    dict(path="/", alt="/en/", title="Wallet Partners | Aceptación de tarjetas para estaciones de combustible en República Dominicana",
         description="Acepte tarjetas en su estación de gasolina y pague 0.25% menos que con su contrato actual. Sin mínimo mensual, liquidación en dólares, terminales para el patio y soporte en Santo Domingo. Wallet Partners LLC.",
         body=home.body, map=True, priority="1.0"),
    dict(path="/como-funciona/", alt="/en/how-it-works/", title="Cómo funciona | Wallet Partners",
         description="Cómo funciona la aceptación de tarjetas de Wallet Partners en estaciones de combustible: autorización, liquidación al día siguiente, conciliación por turno, documentos para afiliarse y terminales para el patio.",
         body=como.body, priority="0.8"),
    dict(path="/precios/", alt="/en/pricing/", title="Precios | Wallet Partners",
         description="25 puntos básicos por debajo de su contrato actual, sin mínimo mensual, terminal en alquiler mensual y liquidación en dólares. Calcule su ahorro con los datos de su estación.",
         body=precios.body, priority="0.9"),
    dict(path="/zona/", alt="/en/launch-zone/", title="Zona de lanzamiento: Polígono Central | Wallet Partners",
         description="Mapa de las 20 estaciones de combustible dentro y alrededor del Polígono Central de Santo Domingo donde Wallet Partners inicia sus instalaciones. Registre su estación para la primera ola.",
         body=zona.body, map=True, priority="0.8"),
    dict(path="/preguntas/", alt="/en/faq/", title="Preguntas frecuentes | Wallet Partners",
         description="Respuestas para dueños de estaciones: bancos, plazos de liquidación, tarjetas aceptadas, costo de terminales, contracargos, documentos y aprobación.",
         body=preguntas.body, priority="0.7"),
    dict(path="/afiliese/", alt="/en/sign-up/", title="Afilie su estación | Wallet Partners",
         description="Registre su estación de combustible en cinco minutos y reciba una propuesta por escrito con su tarifa exacta.",
         body=afiliese.body, priority="0.9"),
    dict(path="/bancos/", alt="/en/banks/", title="Bancos y aliados | Wallet Partners",
         description="Resumen para bancos patrocinadores y aliados: programa vertical de adquirencia para estaciones de combustible en la República Dominicana, división de responsabilidades, marco de cumplimiento y lo que pedimos.",
         body=bancos.body, priority="0.7"),
    dict(path="/nosotros/", alt="/en/about/", title="Nosotros | Wallet Partners LLC",
         description="Wallet Partners LLC es una empresa de pagos dedicada a las estaciones de combustible de la República Dominicana.",
         body=nosotros.body, priority="0.5"),
    dict(path="/contacto/", alt="/en/contact/", title="Contacto | Wallet Partners",
         description="Contacte a Wallet Partners LLC: estaciones, bancos, aliados y prensa.", body=contacto.body, priority="0.6"),
    dict(path="/legal/privacidad/", alt="/en/legal/privacy/", title="Política de privacidad | Wallet Partners", description="Cómo Wallet Partners LLC trata los datos personales, incluida la Ley 172-13.", body=legal.privacy, priority="0.3"),
    dict(path="/legal/terminos/", alt="/en/legal/terms/", title="Términos de uso | Wallet Partners", description="Condiciones de uso del sitio web de Wallet Partners LLC.", body=legal.terms, priority="0.3"),
    dict(path="/legal/cookies/", alt="/en/legal/cookies/", title="Aviso de cookies | Wallet Partners", description="Cookies y almacenamiento local usados por este sitio.", body=legal.cookies, priority="0.3"),
    dict(path="/legal/cumplimiento/", alt="/en/legal/compliance/", title="Marco de cumplimiento | Wallet Partners", description="Programa de cumplimiento de Wallet Partners LLC: PCI DSS, Ley 155-17, Ley 172-13, reglas de las redes y supervisión del banco patrocinador.", body=legal.compliance, priority="0.5"),
    dict(path="/legal/aviso-legal/", alt="/en/legal/notice/", title="Aviso legal | Wallet Partners", description="Identificación de la empresa, marcas y declaraciones del sitio de Wallet Partners LLC.", body=legal.notice, priority="0.3"),
    dict(path="/legal/accesibilidad/", alt="/en/legal/accessibility/", title="Accesibilidad | Wallet Partners", description="Compromisos de accesibilidad del sitio de Wallet Partners LLC.", body=legal.accessibility, priority="0.3"),
    # ---- English mirror ----
    dict(path="/en/", alt="/", lang="en", title="Wallet Partners | Card acceptance for gasoline stations in the Dominican Republic",
         description="Accept cards at your gasoline station and pay 0.25% less than your current contract. No monthly minimum, dollar clearing, forecourt terminals and support in Santo Domingo. Wallet Partners LLC.", body=E.home, map=True, priority="0.9"),
    dict(path="/en/how-it-works/", alt="/como-funciona/", lang="en", title="How it works | Wallet Partners", description="How Wallet Partners' card acceptance works at gasoline stations: authorisation, next-day settlement, reconciliation by shift, onboarding documents and forecourt terminals.", body=E.how, priority="0.7"),
    dict(path="/en/pricing/", alt="/precios/", lang="en", title="Pricing | Wallet Partners", description="25 basis points below your current contract, no monthly minimum, terminal on monthly rental and clearing in US dollars. Calculate your saving with your station's numbers.", body=E.pricing, priority="0.8"),
    dict(path="/en/launch-zone/", alt="/zona/", lang="en", title="Launch zone: Polígono Central | Wallet Partners", description="Map of the 20 gasoline stations inside and around Santo Domingo's Polígono Central where Wallet Partners begins installations. Register your station for the first wave.", body=E.zone, map=True, priority="0.7"),
    dict(path="/en/faq/", alt="/preguntas/", lang="en", title="FAQ | Wallet Partners", description="Answers for station owners: banks, settlement timing, cards accepted, terminal cost, chargebacks, documents and approval.", body=E.faq, priority="0.6"),
    dict(path="/en/sign-up/", alt="/afiliese/", lang="en", title="Sign up your station | Wallet Partners", description="Register your gasoline station in five minutes and receive a written proposal with your exact rate.", body=E.signup, priority="0.8"),
    dict(path="/en/banks/", alt="/bancos/", lang="en", title="Banks & partners | Wallet Partners LLC", description="Summary for sponsoring banks and partners: a vertical fuel-retail acquiring program for the Dominican Republic, responsibilities, compliance framework and the ask.", body=E.banks, priority="0.7"),
    dict(path="/en/about/", alt="/nosotros/", lang="en", title="About | Wallet Partners LLC", description="Wallet Partners LLC is a payments company dedicated to gasoline stations in the Dominican Republic.", body=E.about, priority="0.5"),
    dict(path="/en/contact/", alt="/contacto/", lang="en", title="Contact | Wallet Partners", description="Contact Wallet Partners LLC: stations, banks, partners and press.", body=E.contact, priority="0.6"),
    dict(path="/en/legal/privacy/", alt="/legal/privacidad/", lang="en", title="Privacy policy | Wallet Partners", description="How Wallet Partners LLC handles personal data, including under Law 172-13.", body=E.privacy, priority="0.3"),
    dict(path="/en/legal/terms/", alt="/legal/terminos/", lang="en", title="Terms of use | Wallet Partners", description="Terms governing use of the Wallet Partners LLC website.", body=E.terms, priority="0.3"),
    dict(path="/en/legal/cookies/", alt="/legal/cookies/", lang="en", title="Cookie notice | Wallet Partners", description="Cookies and local storage used by this website.", body=E.cookies, priority="0.3"),
    dict(path="/en/legal/compliance/", alt="/legal/cumplimiento/", lang="en", title="Compliance framework | Wallet Partners", description="Wallet Partners LLC's compliance programme: PCI DSS, Law 155-17, Law 172-13, card-network rules and sponsor-bank oversight.", body=E.compliance, priority="0.5"),
    dict(path="/en/legal/notice/", alt="/legal/aviso-legal/", lang="en", title="Legal notice | Wallet Partners", description="Company identification, trademarks and disclosures for the Wallet Partners LLC website.", body=E.notice, priority="0.3"),
    dict(path="/en/legal/accessibility/", alt="/legal/accesibilidad/", lang="en", title="Accessibility | Wallet Partners", description="Accessibility commitments for the Wallet Partners LLC website.", body=E.accessibility, priority="0.3"),
    dict(path="/404.html", title="Página no encontrada | Wallet Partners", description="La página solicitada no existe.", body=legal.notfound, robots="noindex, nofollow"),
]
