"""Page registry. Each entry: path, title, description, body(ctx) -> HTML fragment."""
import home, stations, market, solution, about, contact, legal, es

PAGES = [
    dict(path="/", title="Wallet Partners LLC | Card processing for gasoline stations in the Dominican Republic",
         description="Wallet Partners LLC brings specialised card acceptance and merchant-of-record services to gasoline stations in Santo Domingo's Polígono Central. 20 warm-pipeline stations mapped, market data and compliance framework for sponsoring banks.",
         body=home.body, map=True, priority="1.0"),
    dict(path="/stations/", title="Station map & pipeline | Wallet Partners LLC",
         description="Interactive map and directory of the 20 gasoline stations in Santo Domingo's Polígono Central that form Wallet Partners' launch pipeline, with hours, brands, coordinates and Street View links.",
         body=stations.body, map=True, priority="0.9"),
    dict(path="/market/", title="Market opportunity | Wallet Partners LLC",
         description="Why fuel retail in the Dominican Republic needs a specialised acquirer: the 2026 ANADEGAS card-fee dispute, RD$41 billion in annual card payments at stations, and card-payment growth data from the Banco Central.",
         body=market.body, priority="0.9"),
    dict(path="/solution/", title="Solution & sponsor-bank program | Wallet Partners LLC",
         description="How Wallet Partners' fuel-retail acquiring program works: merchant onboarding, EMV and contactless terminals, settlement, risk controls, and the role of the sponsoring bank.",
         body=solution.body, priority="0.9"),
    dict(path="/about/", title="About Wallet Partners LLC",
         description="Wallet Partners LLC is a payments company focused on the fuel-retail segment of the Dominican Republic, seeking a sponsoring bank to launch its merchant-of-record program.",
         body=about.body, priority="0.7"),
    dict(path="/contact/", title="Contact | Wallet Partners LLC",
         description="Contact Wallet Partners LLC about sponsorship, partnerships or merchant onboarding for gasoline stations in the Dominican Republic.",
         body=contact.body, priority="0.7"),
    dict(path="/es/", title="Wallet Partners LLC | Procesamiento de tarjetas para estaciones de combustible en República Dominicana",
         description="Resumen ejecutivo en español: Wallet Partners LLC ofrece adquirencia y servicios de comercio registrado (MOR) especializados para estaciones de gasolina en el Polígono Central de Santo Domingo.",
         body=es.body, lang="es", priority="0.8"),
    dict(path="/legal/privacy/", title="Privacy policy | Wallet Partners LLC",
         description="How Wallet Partners LLC collects, uses and protects personal data, including under Dominican Law 172-13 and applicable U.S. law.",
         body=legal.privacy, priority="0.3"),
    dict(path="/legal/terms/", title="Terms of use | Wallet Partners LLC",
         description="Terms governing use of the Wallet Partners LLC website.", body=legal.terms, priority="0.3"),
    dict(path="/legal/cookies/", title="Cookie notice | Wallet Partners LLC",
         description="Cookies and local storage used by this website.", body=legal.cookies, priority="0.3"),
    dict(path="/legal/compliance/", title="Compliance & regulatory framework | Wallet Partners LLC",
         description="Wallet Partners LLC's compliance programme: PCI DSS, AML/CFT under Dominican Law 155-17, data protection under Law 172-13, card-network rules and sponsor-bank oversight.",
         body=legal.compliance, priority="0.6"),
    dict(path="/legal/notice/", title="Legal notice | Wallet Partners LLC",
         description="Company identification, trademark and disclaimer information for the Wallet Partners LLC website.",
         body=legal.notice, priority="0.3"),
    dict(path="/legal/accessibility/", title="Accessibility statement | Wallet Partners LLC",
         description="Accessibility commitments for the Wallet Partners LLC website.", body=legal.accessibility, priority="0.3"),
    dict(path="/404.html", title="Page not found | Wallet Partners LLC", description="The page you requested does not exist.",
         body=legal.notfound, robots="noindex, nofollow"),
]
